# Generated by Django 5.1.7 on 2025-03-24 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignIn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('university', 'University'), ('student', 'Student'), ('companies', 'Companies'), ('minister', 'Minister')], max_length=10),
        ),
        migrations.CreateModel(
            name='companies_Certify_me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('Companies_acount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SignIn.account')),
            ],
        ),
        migrations.CreateModel(
            name='Ministry_Certify_me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('Ministry_acount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SignIn.account')),
            ],
        ),
        migrations.CreateModel(
            name='University_Certify_me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('University_acount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SignIn.account')),
            ],
        ),
    ]
